import { differentials, initialCompany } from "@/lib/constants";
import type { Category, Product, ProductImage, SiteSettings } from "@/lib/types";

const now = new Date("2026-01-01T12:00:00.000Z").toISOString();

export const demoCategories: Category[] = [
  {
    id: "cat-eletronicos",
    name: "Eletrônicos",
    slug: "eletronicos",
    description: "Tecnologia original para rotina, lazer e produtividade.",
    image_url: "/images/hero-imports.png",
    icon: "smartphone",
    sort_order: 1,
    active: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: "cat-perfumaria",
    name: "Perfumaria",
    slug: "perfumaria",
    description: "Fragrâncias importadas com procedência e curadoria.",
    image_url: "/images/hero-imports.png",
    icon: "sparkles",
    sort_order: 2,
    active: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: "cat-acessorios",
    name: "Acessórios para Celular",
    slug: "acessorios-para-celular",
    description: "Carregadores, cabos, capas, suportes e itens premium.",
    image_url: "/images/hero-imports.png",
    icon: "cable",
    sort_order: 3,
    active: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: "cat-farmacia",
    name: "Farmácia",
    slug: "farmacia",
    description: "Produtos de cuidado, bem-estar e uso diário importados.",
    image_url: "/images/hero-imports.png",
    icon: "shield-plus",
    sort_order: 4,
    active: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: "cat-informatica",
    name: "Informática",
    slug: "informatica",
    description: "Periféricos, componentes e acessórios para setup.",
    image_url: "/images/hero-imports.png",
    icon: "laptop",
    sort_order: 5,
    active: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: "cat-utilidades",
    name: "Utilidades Domésticas",
    slug: "utilidades-domesticas",
    description: "Soluções práticas e elegantes para casa.",
    image_url: "/images/hero-imports.png",
    icon: "package",
    sort_order: 6,
    active: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: "cat-importados",
    name: "Produtos Importados",
    slug: "produtos-importados",
    description: "Novidades originais dos EUA e Paraguai.",
    image_url: "/images/hero-imports.png",
    icon: "globe-2",
    sort_order: 7,
    active: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: "cat-diversos",
    name: "Diversos",
    slug: "diversos",
    description: "Itens selecionados para oportunidades e encomendas.",
    image_url: "/images/hero-imports.png",
    icon: "layers-3",
    sort_order: 8,
    active: true,
    created_at: now,
    updated_at: now,
  },
];

function image(id: string, productId: string, alt: string): ProductImage {
  return {
    id,
    product_id: productId,
    url: "/images/hero-imports.png",
    alt_text: alt,
    sort_order: 1,
    is_primary: true,
    created_at: now,
  };
}

export const demoProducts: Product[] = [
  {
    id: "prod-fone-premium",
    category_id: "cat-eletronicos",
    name: "Fone Bluetooth Premium",
    slug: "fone-bluetooth-premium",
    description: "Audio limpo, bateria de longa duração e acabamento sofisticado.",
    full_description:
      "Fone sem fio importado com estojo compacto, conexão estável e construção pensada para uso diário. Ideal para clientes que buscam procedência e experiência premium.",
    price: 389.9,
    currency: "BRL",
    status: "in_stock",
    code: "IMP-AUD-001",
    featured: true,
    active: true,
    sort_order: 1,
    metadata: { origin: "Paraguai" },
    created_at: now,
    updated_at: now,
    category: demoCategories[0],
    images: [image("img-fone-premium", "prod-fone-premium", "Fone Bluetooth Premium")],
  },
  {
    id: "prod-perfume-signature",
    category_id: "cat-perfumaria",
    name: "Perfume Importado Signature",
    slug: "perfume-importado-signature",
    description: "Fragrância marcante com embalagem elegante e original.",
    full_description:
      "Produto de perfumaria importada para quem busca presença, fixação e procedência. Disponível em estoque limitado e também sob consulta para reposição.",
    price: 529.9,
    currency: "BRL",
    status: "in_stock",
    code: "IMP-PER-014",
    featured: true,
    active: true,
    sort_order: 2,
    metadata: { origin: "EUA" },
    created_at: now,
    updated_at: now,
    category: demoCategories[1],
    images: [image("img-perfume", "prod-perfume-signature", "Perfume Importado Signature")],
  },
  {
    id: "prod-carregador-usbc",
    category_id: "cat-acessorios",
    name: "Carregador USB-C Turbo",
    slug: "carregador-usb-c-turbo",
    description: "Carregamento rápido para rotina intensa e dispositivos modernos.",
    full_description:
      "Acessório importado com foco em segurança, eficiência e compatibilidade. Produto recomendado para smartphones, tablets e dispositivos USB-C.",
    price: 129.9,
    currency: "BRL",
    status: "pre_order",
    code: "IMP-CEL-022",
    featured: false,
    active: true,
    sort_order: 3,
    metadata: { origin: "Paraguai" },
    created_at: now,
    updated_at: now,
    category: demoCategories[2],
    images: [image("img-carregador", "prod-carregador-usbc", "Carregador USB-C Turbo")],
  },
  {
    id: "prod-kit-bem-estar",
    category_id: "cat-farmacia",
    name: "Kit Bem-Estar Importado",
    slug: "kit-bem-estar-importado",
    description: "Produtos selecionados para cuidado diário e conveniência.",
    full_description:
      "Curadoria de itens importados de farmácia, com foco em procedência e disponibilidade sob encomenda para reposições específicas.",
    price: 219.9,
    currency: "BRL",
    status: "pre_order",
    code: "IMP-FAR-008",
    featured: false,
    active: true,
    sort_order: 4,
    metadata: { origin: "EUA" },
    created_at: now,
    updated_at: now,
    category: demoCategories[3],
    images: [image("img-kit", "prod-kit-bem-estar", "Kit Bem-Estar Importado")],
  },
  {
    id: "prod-mouse-pro",
    category_id: "cat-informatica",
    name: "Mouse Wireless Pro",
    slug: "mouse-wireless-pro",
    description: "Precisão, ergonomia e visual discreto para setups modernos.",
    full_description:
      "Mouse importado para trabalho e produtividade, com resposta rápida, pegada confortável e design minimalista.",
    price: 259.9,
    currency: "BRL",
    status: "in_stock",
    code: "IMP-INF-031",
    featured: true,
    active: true,
    sort_order: 5,
    metadata: { origin: "Paraguai" },
    created_at: now,
    updated_at: now,
    category: demoCategories[4],
    images: [image("img-mouse", "prod-mouse-pro", "Mouse Wireless Pro")],
  },
  {
    id: "prod-luminaria-smart",
    category_id: "cat-utilidades",
    name: "Luminária Smart Portátil",
    slug: "luminaria-smart-portatil",
    description: "Design elegante para casa, trabalho e viagem.",
    full_description:
      "Luminária compacta com acabamento premium, ideal para ambientes organizados e funcionais. Disponível em lotes limitados.",
    price: 189.9,
    currency: "BRL",
    status: "in_stock",
    code: "IMP-UTI-010",
    featured: false,
    active: true,
    sort_order: 6,
    metadata: { origin: "Paraguai" },
    created_at: now,
    updated_at: now,
    category: demoCategories[5],
    images: [image("img-luminaria", "prod-luminaria-smart", "Luminária Smart Portátil")],
  },
];

export const demoSettings: SiteSettings = {
  id: true,
  company_name: initialCompany.name,
  whatsapp: initialCompany.whatsapp,
  email: initialCompany.email,
  instagram: initialCompany.instagram,
  institutional_text:
    "A Império Imports conecta clientes a produtos importados originais dos Estados Unidos e Paraguai, com curadoria, transparência e atendimento próximo. Trabalhamos com itens em estoque e sob encomenda, sempre priorizando procedência, qualidade e uma experiência de compra segura.",
  hero_title: "Produtos importados originais dos EUA e Paraguai.",
  hero_subtitle:
    "Catálogo premium com eletrônicos, perfumaria, acessórios, informática, farmácia e utilidades domésticas em estoque ou sob encomenda.",
  featured_headline: "Curadoria premium para comprar com confiança.",
  banners: [],
  highlights: differentials.map((label) => ({ label })),
  created_at: now,
  updated_at: now,
};
